"""
models/report_generator.py
──────────────────────────
Generate downloadable PDF and CSV reports for screened candidates.
Uses fpdf2 (pure-Python, no system fonts required).
"""

from __future__ import annotations
import io
import csv
from typing import Any


# ── PDF Report ────────────────────────────────────────────────────────────────

def _safe(text: str) -> str:
    """Strip characters unsupported by the PDF's core latin-1 font."""
    if not isinstance(text, str):
        text = str(text)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def generate_pdf_report(candidate_name: str, result: dict[str, Any]) -> bytes:
    """
    Build a single-candidate PDF report.
    Returns raw bytes ready for st.download_button.
    """
    try:
        from fpdf import FPDF

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        pdf.set_margins(20, 15, 20)

        # ── Header ────────────────────────────────────────────────────
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_text_color(139, 92, 246)
        pdf.cell(0, 10, "Resume Screening AI", ln=True, align="C")

        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(100, 100, 120)
        pdf.cell(0, 7, "Candidate Analysis Report", ln=True, align="C")
        pdf.ln(6)

        # Divider
        pdf.set_draw_color(139, 92, 246)
        pdf.set_line_width(0.5)
        pdf.line(20, pdf.get_y(), 190, pdf.get_y())
        pdf.ln(8)

        # ── Candidate name ────────────────────────────────────────────
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(30, 30, 40)
        pdf.cell(0, 8, f"Candidate: {_safe(candidate_name)}", ln=True)
        pdf.ln(4)

        # ── Score Summary ─────────────────────────────────────────────
        _section(pdf, "Score Summary")
        scores = [
            ("Overall Match",    result.get("overall_match", 0)),
            ("ATS Score",        result.get("ats_score", 0)),
            ("Semantic Match",   result.get("semantic_sim", 0)),
            ("Skill Match",      result.get("skill_match", 0)),
            ("Keyword Match",    result.get("keyword_match", 0)),
            ("Experience",       result.get("experience", 0)),
            ("Education",        result.get("education", 0)),
        ]
        for label, value in scores:
            _score_row(pdf, label, value)
        pdf.ln(4)

        # ── Summary ───────────────────────────────────────────────────
        _section(pdf, "AI Summary")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 65)
        pdf.multi_cell(0, 6, _safe(result.get("summary", "No summary available.")))
        pdf.ln(4)

        # ── Skills ────────────────────────────────────────────────────
        res_skills = result.get("resume_skills", {})
        if res_skills:
            _section(pdf, "Detected Skills")
            for cat, skills in res_skills.items():
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(100, 70, 200)
                pdf.cell(0, 6, _safe(cat) + ":", ln=True)
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(50, 50, 65)
                pdf.cell(0, 5, _safe("  " + ", ".join(skills)), ln=True)
            pdf.ln(4)

        # ── Keywords ──────────────────────────────────────────────────
        missing = result.get("missing_keywords", [])
        if missing:
            _section(pdf, "Missing Keywords to Add")
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(50, 50, 65)
            pdf.multi_cell(0, 5, _safe(", ".join(missing[:20])))
            pdf.ln(4)

        # ── Footer ────────────────────────────────────────────────────
        pdf.set_y(-20)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(150, 150, 170)
        pdf.cell(0, 5, "Generated by Resume Screening AI  -  Powered by ML & Sentence Transformers",
                 align="C")

        return bytes(pdf.output())

    except ImportError:
        # Fallback: plain-text report
        return _text_report(candidate_name, result)


def _section(pdf: Any, title: str) -> None:
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(60, 60, 80)
    pdf.cell(0, 8, title, ln=True)
    pdf.set_draw_color(200, 200, 220)
    pdf.set_line_width(0.2)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(3)


def _score_row(pdf: Any, label: str, value: float) -> None:
    color = (
        (74, 222, 128) if value >= 75 else
        (251, 191, 36) if value >= 50 else
        (248, 113, 113)
    )
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 65)
    pdf.cell(80, 6, f"  {_safe(label)}")
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*color)
    pdf.cell(0, 6, f"{value:.1f}%", ln=True)


def _text_report(name: str, result: dict) -> bytes:
    lines = [
        f"Resume Screening AI — Report for {name}",
        "=" * 50,
        f"Overall Match:   {result.get('overall_match', 0):.1f}%",
        f"ATS Score:       {result.get('ats_score', 0):.1f}%",
        f"Semantic Match:  {result.get('semantic_sim', 0):.1f}%",
        f"Skill Match:     {result.get('skill_match', 0):.1f}%",
        "",
        "Summary:",
        result.get("summary", ""),
    ]
    return "\n".join(lines).encode()


# ── CSV Export ────────────────────────────────────────────────────────────────

def generate_csv_report(candidates: list[dict[str, Any]]) -> bytes:
    """
    Export all candidate results as CSV.
    `candidates` is a list of {'name': str, 'result': dict}.
    """
    output = io.StringIO()
    fields = [
        "Rank", "Candidate", "Overall Match (%)", "ATS Score (%)",
        "Semantic Sim (%)", "Skill Match (%)", "Keyword Match (%)",
        "Experience (%)", "Education (%)", "Word Count",
    ]
    writer = csv.DictWriter(output, fieldnames=fields)
    writer.writeheader()

    for i, cand in enumerate(sorted(
        candidates, key=lambda c: c["result"].get("overall_match", 0), reverse=True
    ), 1):
        r = cand["result"]
        writer.writerow({
            "Rank":               i,
            "Candidate":          cand["name"],
            "Overall Match (%)":  r.get("overall_match", 0),
            "ATS Score (%)":      r.get("ats_score", 0),
            "Semantic Sim (%)":   r.get("semantic_sim", 0),
            "Skill Match (%)":    r.get("skill_match", 0),
            "Keyword Match (%)":  r.get("keyword_match", 0),
            "Experience (%)":     r.get("experience", 0),
            "Education (%)":      r.get("education", 0),
            "Word Count":         r.get("word_count", 0),
        })

    return output.getvalue().encode()
